const countries = [
    { code: 'AUT', name: 'Austria' },
    { code: 'BEL', name: 'Belgium' },
    { code: 'BGR', name: 'Bulgaria' },
    { code: 'CN', name: 'China' },
    { code: 'HRV', name: 'Croatia' },
    { code: 'CYP', name: 'Cyprus' },
    { code: 'CZE', name: 'Czechia' },
    { code: 'DNK', name: 'Denmark' },
    { code: 'EU-27', name: 'EU-27' },
    { code: 'EU27+1', name: 'EU27+1' },
    { code: 'EST', name: 'Estonia' },
    { code: 'FIN', name: 'Finland' },
    { code: 'FRA', name: 'France' },
    { code: 'DEU', name: 'Germany' },
    { code: 'GRC', name: 'Greece' },
    { code: 'HUN', name: 'Hungary' },
    { code: 'IRL', name: 'Ireland' },
    { code: 'ITA', name: 'Italy' },
    { code: 'LVA', name: 'Latvia' },
    { code: 'LTU', name: 'Lithuania' },
    { code: 'LUX', name: 'Luxembourg' },
    { code: 'MLT', name: 'Malta' },
    { code: 'NLD', name: 'Netherlands' },
    { code: 'POL', name: 'Poland' },
    { code: 'PRT', name: 'Portugal' },
    { code: 'ROU', name: 'Romania' },
    { code: 'SVK', name: 'Slovakia' },
    { code: 'SVN', name: 'Slovenia' },
    { code: 'ESP', name: 'Spain' },
    { code: 'SWE', name: 'Sweden' },
    { code: 'USA', name: 'United States' },
    { code: 'GBR', name: 'United Kingdom' }
  ];

    export default countries;
